apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-prometheus
spec:
  scaleTargetRef:
    name: nginx
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      metricName: memory_usage
      query: sum(container_memory_working_set_bytes{container="nginx"})
      serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      threshold: "25000000"
      activationThreshold: "0"
